### ISSUE TITLE
Emoji selector is too wide with large emoji lists

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1027]
![stretched emoji selector](https://cloud.githubusercontent.com/assets/4358079/5832022/e90d43b0-a0f2-11e4-9921-1ccb215ba34e.png)

Reproduce:
- Download and install http://kde-look.org/content/show.php/Google+Hangout+Emojis+Complete?content=162161
- Restart qTox
- Select GoogleEmojiComplete as the Smiley Pack in Settings
- Open a conversation and click the smiley button

**Comment by dubslow** [comment]
@apprb @krepa098

**Comment by apprb** [comment]
I really want to help, but unfortunatelly till the end of this month (or even more) I'm very busy with my work.

**Comment by krepa098** [comment]
![text4615-9-1-6](https://cloud.githubusercontent.com/assets/4587853/6087771/c7204c92-ae4f-11e4-8805-509c8801863e.png)

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by ProMcTagonist** [comment]
@krepa098 has the right idea. The popup should be remodeled after Facebook's, in preparation for stickers.
![popup](https://cloud.githubusercontent.com/assets/4358079/6088836/91e9a19e-ae0f-11e4-8d6c-9ebb7353e285.jpg)

**Comment by redsteakraw** [comment]
This was fixed when the emoticon widget was switched to an 8x8 grid.  @dubslow

**Comment by ProMcTagonist** [comment]
No, it wasn't. The current implementation is fundamentally flawed. It will be a problem again with larger lists of emoji and TwitterEmojiSVG is still misaligned because of the long row of pager dots. It needs this redesign.

A note, the tab bar should be vertical and on the side, because it's awkward and unpleasant to navigate Facebook's horizontal one.

**Comment by redsteakraw** [comment]
@ProMcTagonist  this was a bug not a feature request as far as bugs are concerned it was fixed, there isn't a huge list for large Emoji sets as far as what your feature request should be filed separately and this should be closed.

**Comment by ProMcTagonist** [comment]
The core problem isn't fixed, 
![emoji paginator too wide](https://cloud.githubusercontent.com/assets/4358079/6374488/150e5fd2-bcc6-11e4-8131-d5b1bb8269e3.png)
and will get worse again whenever increasingly longer lists of emoticons are used. This is because the problem is inherent to the current pagination model. 

But because it fits in the window and TwitterEmojiSVG is the biggest pack anyone's likely to use, I'll close this.

**Comment by redsteakraw** [comment]
@ProMcTagonist  I agree there needs to be an overhaul Unicode has a draft for official emoji ordering and grouping.  I would file a feature request for emoji grouping.

**Comment by ProMcTagonist** [comment]
@redsteakraw 
Many emoji need to be in packs so that there's support and they're displayed when received. But not as many are regularly sent. It would be useful to be able to specify only certain emoticons to appear in the emoticon section of the redesigned popup (with the rest hidden, but still displayed when received), because much of their current uses will be superseded by stickers.

**Comment by zetok** [comment]
@ProMcTagonist I think that redesign still should be done, and it still doesn't seem to be really "fixed" in your last screenshot. Not to mention that people being people may use a lot more than what's provided in qTox's emoticon packs… (i.e. custom emoticons)

(reopen?)

**Comment by ProMcTagonist** [comment]
@zetok I closed it based on the unlikeliness that any normal user would encounter a problem like in the OP anytime soon. I doubt anyone will be creating and using emoticon packs twice as large as TwitterEmojiSVG.

The only way for this issue to technically be fixed forever is the redesign. And the redesign is really centered around stickers. It seems like a lot of wasted effort to knowingly redesign it twice. 

That's my reasoning for closing this.

I plan on making a feature request issue for the redesign. Should it be done now so we can move discussion there, even though stickers aren't implemented yet?

**Comment by zetok** [comment]
@ProMcTagonist but there's no issue for stickers redesign..?

EDIT: _oh that ninja edit_

> I plan on making a feature request issue for the redesign. Should it be done now so we can move discussion there, even though stickers aren't implemented yet?

Yes, and link to this issue.

**Comment by ProMcTagonist** [comment]
@zetok #1294

EDIT: sorry for ninja editing before :)
