### ISSUE TITLE
qtox crash at audio/video options

### ISSUE THREAD

**Issue by GitHub-devel** [qTox/qTox#1414]
**Description:**

gdb output:
https://gist.github.com/GitHub-devel/5c5714d00a878f444f95

valgrind output:
https://gist.github.com/GitHub-devel/cecd74826e324655d590

Info: Qt 5.4.1, Xorg 1.16.1, glibc 2.19
OS: openSUSE 13.2 x86_64

**Reproducible: Always**

**Steps to reproduce:**
1. start qtox
2. choose options -> audio/video

**What happened:**

qtox crashes

**What should happen:**

qtox showing audio/video options

**Additional info:**

Since using X-Forwarding it is similar to this:
https://bugreports.qt.io/browse/QTBUG-31354
https://bugreports.qt.io/browse/QTCREATORBUG-11173

Workaround for this can be good too.

**Comment by dubslow** [comment]
We've had many, many many reports of this, and it's not something I'm too familiar with. Someone suggested it was an OpenCV issue.

**Comment by GitHub-devel** [comment]
Is it possible to start qtox without video support, so you can use audio/video settings for audio only, for example, without crash ?

**Comment by sudden6** [comment]
that someone was probably me and I have got a little further: https://github.com/tux3/qTox/commit/68afc8f623519b6c92f92a1d1fc4896df5522b8f

**Comment by sudden6** [comment]
@GitHub-devel can you test again? It should be fixed now.

**Comment by GitHub-devel** [comment]
Checked with latest git - the crash still here with the exact same output.

**Comment by sudden6** [comment]
@GitHub-devel checked your bug report again, seems that it is not a duplicate of #1240
The bad news are that this seems to be a bug in qt and won't probably get fixed, if you don't do it yourself.

@dubslow this is not a duplicate of #1240

**Comment by tux3** [comment]
We may want to try to reimplement VideoSurface differently to work around this bug, since so many people seem to be affected by it (or variations of it).

**Comment by sudden6** [comment]
What about generally using Gstreamer for audio/video?
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/qt-gstreamer/html/qtvideosink_overview.html
looks like it won't be to complicated

**Comment by tux3** [comment]
This should be fixed with FFmpeg.
