### ISSUE TITLE
Sending a message to someone with the new API gets resent endlessly

### ISSUE THREAD

**Issue by itsrachelfish** [qTox/qTox#1506]
Example:

```
[pending] rachel fish: hello?
[22:50] Groupbot: lid command. Type help for a list of commands
[22:50] Groupbot: lid command. Type help for a list of commands
[22:51] Groupbot: lid command. Type help for a list of commands
[22:51] Groupbot: lid command. Type help for a list of commands
```

**Comment by ProMcTagonist** [comment]
I get it too. I just removed Groupbot. Should be fixed this Monday, right?

**Comment by mdev88** [comment]
This is still happening with the latest dmg available on the web today.

**Comment by tux3** [comment]
@martinchodev We're currently working on a qTox version with the new API, and it's almost ready but in the meantime new and old clients aren't compatible.

The new version and the new .dmg will only come out on Monday to make sure it's as stable as possible!

**Comment by mdev88** [comment]
Excellent! We'll try that one and see what happens.

**Comment by tux3** [comment]
Fixed in the new API branch.

**Comment by zetok** [comment]
I don't think that it was fixed, since a real fix would be an ability to turn off faux offline messages, which was possible before, but not any longer.

Also, contact blocking / ignoring could help with stuff like that.

**Comment by tux3** [comment]
Contact blocking/ignoring is going to be added, but imo that's a separate issue.

There's no way to prevent people on old versions of qTox having this bug. If we made a fix they'd have to update to get the fix, and then they'd be on the new API, so the problem would be solved :)

**Comment by itsrachelfish** [comment]
@zetok @tux3 Actually, if you "clear" the message log it prevents "offline messages" like these from being resent endlessly. May be useful for anyone who is currently stuck using an old version of qTox. :)
