### ISSUE TITLE
qTox shouldn't make invalid tox links

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#2118]
Tox links can be either `tox:‹toxid›` or `tox:‹name›@‹domain›`. Everything else should not be interpreted as links.

**Comment by zetok** [comment]
e.g. ![link](https://cloud.githubusercontent.com/assets/3148759/9495178/1e41df7c-4c02-11e5-8277-a5cfd50efa2b.png) shouldn't be interpreted as Tox link.

**Comment by agilob** [comment]
Why is tox://ID invalid?

**Comment by suhr** [comment]
`asdf123123` is definitely not an id.

**Comment by agilob** [comment]
> - e.g.  - example

I know asdf123123 is not valid, but why tox://ID is invalid?

**Comment by suhr** [comment]
https://github.com/Tox/Tox-STS/blob/master/STS.md#tox-uri-scheme

**Comment by agilob** [comment]
Ok, I fixed this, whole regexps detecting URI is improved now:

![snapshot4](https://cloud.githubusercontent.com/assets/2544251/9564789/b3c6d1b2-4ea8-11e5-90d9-91027dc1b247.png)

**Comment by suhr** [comment]
**Not fixed:** `tox:A5` is still highlighted. It should highlight either `tox:‹toxid long hex›` or `tox:‹name›@domain`. The “toxid long” detail is very important: whether toxid is clipped, user should know about it.

**Comment by agilob** [comment]
How long is tox id with and without nospam?

**Comment by zetok** [comment]
64 upper-case chars (and numbers) without nospam+checksum, and with those, 76

**Comment by agilob** [comment]
It will be fixed today with profile importer, no need to reopen.

**Comment by suhr** [comment]
It shouldn't accept publickey without nospam+checksum though.

**Comment by zetok** [comment]
So 76 it is.

**Comment by agilob** [comment]
oki

**Comment by agilob** [comment]
anything else?

![snapshot5](https://cloud.githubusercontent.com/assets/2544251/9566370/e2808db6-4efa-11e5-8743-84b0ea54b91f.png)
