### ISSUE TITLE
 Call audio interference

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2609]
In previous versions of the program calls work well. Today in the Commit hash version: 0ef39aa06af177061ab53c259ee9c71de2876264 call audio is heard noises and can not understand the person.

**Comment by ghost** [comment]
Do you know which commit hash you were using previously? 0ef39aa06af177061ab53c259ee9c71de2876264 is certainly not responsible for a worse audio quality.

**Comment by dcapeletti** [comment]
A month ago, everything worked fine. I have no idea that change is the responzable that noise is heard in the audio.

**Comment by ghost** [comment]
Not sure if the OP is referring to the same issue, but I'm also having trouble with group chats. One to one voice chats are working fine as always, but recently group voice chats became completely unusable; as soon as a third person enters voice, all other participants start intermittently dropping (you can only hear fragments of their speech) and distorting. Everything returns to normal as soon as the amount of participants returns to 2. So both group chats and individual chats are working fine, as long as there is a maximum of two participants.

I'm not sure, but I think it is related to the new A/V API, both me and my peers only updated qTox once recently and that was after the new A/V API was pushed, which is when it started happening.

**Comment by ghost** [comment]
I just had a call with someone where they could hear me most of the time, but I could barely hear them... Plus it really did make us sound like Daleks! :D

**Comment by dcapeletti** [comment]
In the client utox there is no annoying noise. Besides the video call, it works quite well in utox.

**Comment by ghost** [comment]
#2577?

**Comment by tux3** [comment]
This might have been a problem with filter audio, could someone check if this is still an issue on the latest qTox?

**Comment by ghost** [comment]
I have checked, and the problem still remains. I also tried using the "audio filtering" option, but it's no use, it doesn't seem to make even the slightest difference...

**Comment by antis81** [comment]
Should be fixed in #2509 -> @tux3 Please read my comment…

**Comment by Ineluki** [comment]
Can confirm the problem. Has been broken for ~5 weeks. Probably since https://github.com/tux3/qTox/commit/f45256baf161a6072062c6df3bcfb0aa026144b0

It was still broken in https://github.com/tux3/qTox/commit/1874c0ce4d878f1a179894900431c68f3c751eb9

**Comment by antis81** [comment]
Closing this one -> fixed upstream.
