### ISSUE TITLE
Unable to update qtox

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2624]
Hello, i'm having a issue while updating qtox with sudo apt-get update && sudo apt-get upgrade, it says:

WARNING: The following packages can not be authenticated.
   qtox
Install these packages without verification? [y / N] y
Err https://pkg.tox.chat/debian/ nightly / release qtox amd64 278-1874c0c
   Failed to connect to pkg.tox.chat port 443: The network is not reachable
E: Can not retrieve https://pkg.tox.chat/debian/pool/release/q/qtox/qtox_278-1874c0c_amd64.deb Failed to connect to pkg.tox.chat port 443: The network is not reachable

i've added the gpg key, it was always working before.

OS: Debian jessie 3.16.0-4-amd64

**Comment by tux3** [comment]
We've been working on the infrastructure recently so it's possible things are a bit unstable, there will be new repositories soon and it should work better.

**Comment by Zer0-One** [comment]
@Twyz are you still having this issue?

**Comment by ghost** [comment]
yes

**Comment by tux3** [comment]
This should be fixed now.

**Comment by ghost** [comment]
Still same error.

**Comment by tux3** [comment]
@Zer0-One any idea?

**Comment by Zer0-One** [comment]
@Twyz what country do you live in? are you able to resolve the domain? Is your border firewall blocking access to .chat domains?

**Comment by ghost** [comment]
I live in Italy, i can access to the website but i can't ping the site from the terminal.

**Comment by Zer0-One** [comment]
Do you use a proxy to access pkg.tox.chat from your browser?

**Comment by ghost** [comment]
no

**Comment by Zer0-One** [comment]
Well, so far it isn't sounding like an issue on our end. Do you know of anyone else having the same issue?

**Comment by ghost** [comment]
i don't know anyone, maybe it's only my issue.

**Comment by agilob** [comment]
I consulted with @Twyz on tox, he can download .deb using browser and using wget (both as user and with sudo), so it was not our problem. 

We fixed it by doing:

```
[19:20:36] agilob: please do:
sudo apt-get clean
sudo apt-get autoremove
[19:20:53] agilob: and then
sudo apt-get update
sudo apt-get upgrade
```

So it looks like it was a wired caching apt-get/dns problem?

**Comment by arunk** [comment]
I am still facing this issue. I tried the instructions above, clean and autoremove. But apt-get update still fails with "Failed to connect to pkg.tox.chat port 443: Network is unreachable"

**Comment by tux3** [comment]
This is probably on our end, given how many times this has been reported.
"Network is unreachable" could mean the port at pkg.tox.chat:443 is somehow seen as closed or firewalled.

**Comment by Zer0-One** [comment]
@tux3  this isn't a firewall issue.

@arunk what country are you in? are you able to reach pkg.tox.chat via your browser? via wget? do you use a proxy to access the internet?

**Comment by Zer0-One** [comment]
@arunk also, copy+paste your sources.list for me

**Comment by arunk** [comment]
@Zer0-One i live in india. i'm able to view pkg.tox.chat via browser, and wget. i don't use a proxy to access the internet, and i have now tried to run update both at home as well as at a friend's place.

here is my tox.list from sources.list.d:
deb https://pkg.tox.chat/debian nightly release

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by tts3c** [comment]
Installing from Linux mint 17.3 based on ubuntu trusty. Cannot install as https://pkg.tox.chat/debian/dists/stable/trusty/binary-i386/Packages is empty. Are there no packages for Ubuntu trusty? Thanks for the help.

**Comment by zetok** [comment]
@taimoortalpur you have tried the link in INSTALL.md?

**Comment by tts3c** [comment]
Thanks zetok,
I was trying since yesterday, finally the Community builds in the INSTALL.md worked. Thanks.

**Comment by zetok** [comment]
No response for over a month from @Twyz, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Comment by kcg295** [comment]
Hello! I am having a package authentication error on Debian 8.

```
user@debian-8:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  qtox
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.6 MB of archives.
After this operation, 48.1 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  qtox
Install these packages without verification? [y/N] n
E: Some packages could not be authenticated
```

I have done the following steps to try to fix this error:

1. `sudo apt-get update && sudo apt-get upgrade`
2. `sudo apt-key update`
3. `wget http://download.opensuse.org/repositories/home:antonbatenev:tox/Debian_8.0/Release.key && sudo apt-key add - < Release.key && sudo apt-get update && sudo apt-get upgrade`

(3rd step as per https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox)

When I check apt-key list I see that the key that I got from step 3 above is expired.

```
pub   2048R/5EF8303B 2014-09-04 [expired: 2016-11-12]
uid                  home:antonbatenev OBS Project <home:antonbatenev@build.opensuse.org>
```

Any help? Is there something I'm doing wrong?

Thanks.

**Comment by zetok** [comment]
@kcg295 https://qtox.github.io/blog/2016/11/13/Expired-GPG-and-v1.6.0-release.html

Weird though, the key I get from wget is:
```
$ gpg --list-packets Release.key 
gpg: using character set 'utf-8'
gpg: armor: BEGIN PGP PUBLIC KEY BLOCK
gpg: armor header: Version: GnuPG v1.4.5 (GNU/Linux)
# off=0 ctb=99 tag=6 hlen=3 plen=269
:public key packet:
	version 4, algo 1, created 1409839636, expires 0
	pkey[0]: [2048 bits]
	pkey[1]: [17 bits]
	keyid: F2AA0B1E5EF8303B
# off=272 ctb=b4 tag=13 hlen=2 plen=68
:user ID packet: "home:antonbatenev OBS Project <home:antonbatenev@build.opensuse.org>"
# off=342 ctb=89 tag=2 hlen=3 plen=318
:signature packet: algo 1, keyid F2AA0B1E5EF8303B
	version 4, created 1478994239, md5len 0, sigclass 0x13
	digest algo 2, begin of digest 2d 9f
	hashed subpkt 2 len 4 (sig created 2016-11-12)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 4y140d9h36m)
	hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID F2AA0B1E5EF8303B)
	data: [2046 bits]
# off=663 ctb=88 tag=2 hlen=2 plen=70
:signature packet: algo 17, keyid 3B3011B76B9D6523
	version 4, created 1409839636, md5len 0, sigclass 0x13
	digest algo 2, begin of digest 5b 85
	hashed subpkt 2 len 4 (sig created 2014-09-04)
	subpkt 16 len 8 (issuer key ID 3B3011B76B9D6523)
	data: [159 bits]
	data: [160 bits]
```
The relevant part:
```
	hashed subpkt 2 len 4 (sig created 2016-11-12)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 4y140d9h36m)
```
Which makes me wonder if you were adding the right (new) `Release.key` ?

**Comment by kcg295** [comment]
The problem was my own stupidity. Sorry for the confusion. It's fixed.
