### ISSUE TITLE
qTox fails to start after sesion crash

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2691]
Steps to reproduce
- `$ ./qtox`, log in, kill it
- `$ ./qtox` again

> [10:10:55.409] src/persistence/settings.cpp:120 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
> [10:10:55.410] src/ipc.cpp:46 : Debug: Our global IPC ID is  3355177397969370
> [10:10:55.410] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
> [10:10:55.410] src/main.cpp:143 : Debug: built on:  09:44:35 Dec 16 2015 ( 1450255438 )
> [10:10:55.410] src/main.cpp:144 : Debug: commit:  22ddef48b192e80f7159ea78e65aa606e914c950 
> 
> [10:10:55.410] src/ipc.cpp:125 : Debug: postEvent  "activate" to 0

It can also be reproduced by
- `$ ./qtox -p bob`, log in, kill it
- `$ ./qtox` again

It only crashes if the second time is started without the `-p` flag. Otherwise, it outputs

> Debug: Previous owner timed out, taking ownership 1234567892584125550 -> 12345678931945561169

and continues normally.

Probably the same issue mentioned by @sudden6 here https://github.com/tux3/qTox/issues/2608#issuecomment-161001719. Maybe related to #2408?

**Comment by tux3** [comment]
This should be fixed by af59b5b45adae043cfe1bbd2afb766955a3279e6, what version are you running?

**Comment by ghost** [comment]
22ddef48b192e80f7159ea78e65aa606e914c950 so no, af59b5b45adae043cfe1bbd2afb766955a3279e6 didn't fix it.

**Comment by tux3** [comment]
I can't repro, it starts normally for me.
If it actually crashes and doesn't exit cleanly, can you get a backtrace?

**Comment by ovalseven8** [comment]
Seems to be related to https://github.com/tux3/qTox/issues/2480#issuecomment-154075390.

**Comment by ghost** [comment]
Couldn't reproduce with `gdb`, and now I'm having difficulties reproducing with the same builds I used to test 4 hours ago. The closest I could get, after killing qTox several times, was

> $ ./qtox -p bob
> [14:37:07.348] src/persistence/settings.cpp:120 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
> [14:37:07.348] src/ipc.cpp:46 : Debug: Our global IPC ID is  123
> [14:37:07.349] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
> [14:37:07.349] src/main.cpp:143 : Debug: built on:  Dec 16 2015 ( 1450255438 )
> [14:37:07.349] src/main.cpp:144 : Debug: commit:  22ddef48b192e80f7159ea78e65aa606e914c950 
> 
> [14:37:07.349] src/main.cpp:171 : Debug: Setting profile to "bob"
> [14:37:07.349] src/nexus.cpp:82 : Debug: Starting up
> [14:37:08.400] src/ipc.cpp:258 : Debug: Previous owner timed out, taking ownership 789 -> 123

`CTRL` + `c`

> $ ./qtox
> [14:37:15.371] src/persistence/settings.cpp:120 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
> [14:37:15.372] src/ipc.cpp:46 : Debug: Our global IPC ID is  456
> [14:37:15.372] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
> [14:37:15.372] src/main.cpp:143 : Debug: built on:  Dec 16 2015 ( 1450255438 )
> [14:37:15.372] src/main.cpp:144 : Debug: commit:  22ddef48b192e80f7159ea78e65aa606e914c950 
> 
> [14:37:15.373] src/ipc.cpp:125 : Debug: postEvent  "activate" to 0
> [14:37:16.421] src/ipc.cpp:258 : Debug: Previous owner timed out, taking ownership 123 -> 456

Notice that the second time qTox was called, it took ownership of the killed instance.

---

btw, this is self-compiled, Qt 5.5.1 in Debian testing.

And I forgot to mention that it fails to start once, but if runs normally the next time.

**Comment by tux3** [comment]
Yes, it's supposed to take ownership in this case, so that's not a bug. I'm pretty sure this bug is fixed now.

Also, you don't have to edit out the IPC ownership numbers, they are really just random numbers.

**Comment by ghost** [comment]
I'm able to reproduce again. Freshly compiled 3717b5c98d97e95b64590263204e5e403829568b. But it just won't fail in `gdb`. No matter if I make the first run (the one that's killed) with or without `gdb`. The steps and results are as in the first post.

Can reproduce with the latest binaries (3717b5c98d97e95b64590263204e5e403829568b) too.

A clarification about my latest comment: after taking ownership, qTox finished. There was no login screen.

> don't have to edit out the IPC ownership numbers

Thanks for the tip!

**Comment by tux3** [comment]
@kehugter Note that if qTox crashes, it will take 2s for the crashed instance to timeout, so if you restart qTox without waiting 2s it will think there's another instance running and exit normally.

**Comment by ghost** [comment]
> 2s

That was it :)
