### ISSUE TITLE
Audio in audio/video calls doesn't work properly anymore

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2704]
Hello,

if you make an audio call, the audio (outgoing) doesn't work for moments and if your volume is very high it doesn't work at all.
So, unfortunately audio calls aren't really possible with qTox at the moment.

**Comment by tux3** [comment]
@antis81

**Comment by antis81** [comment]
@ovalseven8 Hm… do you have some log output for me?

**EDIT** Can you please post the hardware & OS specs of the machine you're working with?

**Comment by ovalseven8** [comment]
@antis81:
Unfortunately, there's no interesting log output.

OS: Lubuntu 14.04
Audio device [0403]: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller
Kernel driver in use: snd_hda_intel

**Comment by antis81** [comment]
This is very similar to my specs:
Lubuntu 14.04 on macbook 2,1
Audio device: Intel Corporation NM10/ICH7 Family High Definition Audio Controller (rev 02)
Kernel driver: snd_hda_intel

What's interesting to me in the logfile are the `subscribe/unsubscribe audio` lines and `Open/Close audio`, maybe also the `created/deleted audio source` lines.

Btw.: Are you running more than one qTox instance for the test?

**Comment by ovalseven8** [comment]
Yes, more than one qTox instance.

**Comment by antis81** [comment]
Ok, that explains some things (see #2706)… :+1: :smile:

Our A/V resource management actually doesn't share resources yet accross qTox instances, which leads to problems in running two or more qTox instances within the same environment.

@tux3 Should we share A/V resources accross qTox instances? And if, any idea for a concept?

**Comment by ovalseven8** [comment]
Would be cool if it's still possible to use more than one qTox instance to make audio/video calls.

**Comment by tux3** [comment]
@antis81 Why would you need to share resources across instances?
Two applications can use sound independently of each other.

**Comment by antis81** [comment]
> Why would you need to share resources across instances?

Actually two qTox instances (and maybe a video running besides while chatting) are always sharing the same hardware (soundcard). That's a given fact. What I mean is: Allowing qTox to call another instance on the same hardware (start qTox 2 times and place a call to the second instance) obviously leads to problems.

While thinking about it, @ovalseven8 you probably get a lot of those nasty "resource not available" messages, right? This is, because we can stream from several input channels (devices/sources) to one output device (usually called "master out"). But when it comes to the microphone (input device) - well there's only one. In the "common setup", there's only one microphone available and when opening this from one instance, it is blocked to other applications (-> "resource not available"). When trying to call two qTox instances using the same input source, I get what I expect -> trouble. :smile:

Think about a musician who tries to play two songs at the same time and then trying to record them to two separate tapes (mp3's or whatever). Wouldn't that be a bit weird? That's exactly what we're trying to do.

> Two applications can use sound independently of each other.

By the above being said, for the output device -> yes; For the input device -> no (we need two separate input sources) - :smile:

Of course we can still run two qTox instances and having one audio conversation while chatting on the other - or one instance by starting a group call. Calling a second person from the second instance means -> stream input from one application to another (see #2545).

Confusion overflow… need to cool my head off… :)

**Comment by ovalseven8** [comment]
@antis81:
Well, I suppose there's some other bug.
The interaction between my USB headset mono (Instance 1) and Monitor stereo (Instance 2) of it doesn't work.

```
AL lib: (EE) LoadHrtf: Could not open default-44100.mhr
AL lib: (EE) GetHrtf: Incompatible format: Stereo 44100hz
```

**Comment by antis81** [comment]
Uhm… IIRC, there's no mono/stereo/... detection yet. We always expect stereo input. @tux3 Right?

**Comment by ovalseven8** [comment]
@antis81:
Did some further testings. It doesn't matter if it's a video or audio call. 
There's a profound bug somewhere, the audio is going crazy sometimes but it's very hard to keep track of it.

Here my qTox log from today while I played around with two instances. Perhaps it can help for whatever: http://pastebin.com/QL7cfxPM

**Comment by antis81** [comment]
That sounds like if the audio buffers are not initialized correctly -> and that's caused by some parameters (like how many channels, sampling rate, etc.), which we still define as the following constants in `audio.h`:

``` c++
// Public default audio settings
static constexpr uint32_t AUDIO_SAMPLE_RATE = 48000; ///< The next best Opus would take is 24k
static constexpr uint32_t AUDIO_FRAME_DURATION = 20; ///< In milliseconds
static constexpr uint32_t AUDIO_FRAME_SAMPLE_COUNT = AUDIO_FRAME_DURATION * AUDIO_SAMPLE_RATE/1000;
static constexpr uint32_t AUDIO_CHANNELS = 2; ///< Ideally, we'd auto-detect, but that's a sane default
```

That means, if the audio in/out device doesn't support these settings, the buffers are not correctly initialized. So… there's another bit of work to do -> we need to actually detect the audio device's capabilities and find the optimum settings for reliable and smooth audio transmission.

**Comment by ovalseven8** [comment]
I see. What's strange, however, is that I never had those issues before.

Thanks for your work, @antis81!

**Comment by tux3** [comment]
@antis81 

> What I mean is: Allowing qTox to call another instance on the same hardware (start qTox 2 times and place a call to the second instance) obviously leads to problems.

Ok, I can see what you mean now. On my system I can hapilly have 2 qTox instances using the same microphone and speakers, since PulseAudio takes care of doing the sharing, so that's why I don't see this problem.

> hm… IIRC, there's no mono/stereo/... detection yet. We always expect stereo input. @tux3 Right?

Yep.

**Comment by antis81** [comment]
@ovalseven8 Can you recheck please (if you find some time of course)? Might be because of a double subscription to output, which I fixed recently in #2719.

**Comment by ovalseven8** [comment]
@antis81:
Unfortunately, I am not able to make a call anymore. If I start two instances and make a call both are crashing:
```
[08:42:36.891] src/core/coreav.cpp:177 : Debug: "Starting call with 0"
[08:42:36.891] src/audio/audio.cpp:411 : Debug: Opening audio input "none"
[08:42:36.891] src/audio/audio.cpp:388 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[08:42:36.891] src/audio/audio.cpp:468 : Debug: Opening audio output "none"
qtox: src/audio/audio.cpp:752: void Audio::subscribeOutput(Audio::SID&): Zusicherung »sid« nicht erfüllt.
```

**Comment by ovalseven8** [comment]
@antis81:
It's definitely better now. Thanks for that.
But it's not solved yet. For example if I have two instances and one of it is using my USB headset as capture device and the other instance 'Monitor of Intern Audio' as capture device, the sound is going crazy again.

Audio: http://picosong.com/Qxur/

Audio settings of the two instances:
![2015-12-24-092540_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/11991954/75dd71e8-aa20-11e5-9e8f-06a22ad439cf.png)
![2015-12-24-092550_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/11991962/7afb71ac-aa20-11e5-9f3e-d38fd0c25ee1.png)

**Comment by antis81** [comment]
@ovalseven8 Thanks for the audio recording. Let me know when you plan your next hijack coup. :)

What we hear is two effects: The well known echo/delay plus low pitched voice (probably with speed unchanged). They appear to origin from the same error source, called feedback. That means: The mic records what the speaker tells (with a tiny time delay), causing an "infinite loop". To analyze what's happening physically, we'd need a spectrum analyzer and some tools… But the answers are simple:
1. **Increase the distance between speaker and mic and/or decrease in-/output volume -> echo should then stop and the effects should disappear.**
2. Stop talking to yourself and call another person (echobot maybe) or a group.

As you can see, we're just starting with a/v concepts and for me (and probably lots of other people), this is actually the first time, that I am able to call another person with qTox without running into the following situation:

```
Hi, are you there? … I cannot hear you… Oh, now I can … no, no I was wrong… One moment I try something… *fiddling with volume*… Now can you hear me?… Hello… ah damn f***ing sh** ********** qTox is (/&"§(/&%!§* *** ** ** *** ** * * * ** - Ok, love you bye!"
```

Does that sound familiar? :smile:

**Comment by ovalseven8** [comment]
@antis81:
Well, I was using a headset and because of that the echo problem should be small. 

What's strange is that this problem didn't exist in the past. At least, I couldn't discover it.

**Comment by antis81** [comment]
> Well, I was using a headset and because of that the echo problem should be small.

The screenshots you posted above are showing another setup. Please check and clean up your setup.

> What's strange is that this problem didn't exist in the past. At least, I couldn't discover it.

It is not a problem at all. It's a physical effect, which can be fixed by cleaning up the audio setup in the first place.

My question is:
Are you able to call another person by using your headset with a single qTox instance?

**Comment by tux3** [comment]
> > What's strange is that this problem didn't exist in the past. At least, I couldn't discover it.
> 
> It is not a problem at all. It's a physical effect, which can be fixed by cleaning up the audio setup in the first place.

If it worked before, then it's a regression and it needs to get fixed.
It's not the user's job to workaround our bugs :)

**Comment by antis81** [comment]
@tux3 Maybe you can interpret what the **it** is, which is not working here? I can't. What I can tell is, qTox now works in the majority of common call setups (call & group-call). Now what's not working? :)

**Comment by ovalseven8** [comment]
Yeah, qTox is working in a way that everybody should be able to make audio/video calls.
Nonetheless, there seem to be some things to improve and some things that are probably regressions. Perhaps there're problems with more than one qTox instance?

Would like to encourage everyone to play around with two qTox instances and with different audio settings. Optimally, with an additional headset.

For example, is the following output really the normal behaviour?

---

**Alice:**
Playback: Intern Audio Analog Stereo
Capture: USB Analog Mono

**Bob:**
Playback: USB Analog Stereo
Capture: Monitor of Intern Audio

**_Result:**_
http://picosong.com/Esb7/
(I didn't say anything)

---

**Alice:**
Playback: USB Analog Stereo
Capture: USB Analog Mono

**Bob:**
Playback: USB Analog Stereo
Capture: Monitor USB Analog Stereo

**_Result:**_
http://picosong.com/EsE6/
(Didn't say anything as well)

---

**Comment by antis81** [comment]
@ovalseven8
As you might have noticed, we currently record fixed stereo (@tux3, remember? :smile:). To allow mixing mono/stereo capture devices, we need to autodetect the devices ablities. This is yet to be done.

**Comment by antis81** [comment]
Going to close this discussion, as audio input gain is fixed now and about to land in upstream release soon by PR #3311.

@ovalseven8 If you like, feel free to fetch and compile the PR. It is still subject to change (being rebased) and I highly recommend fetch instead of pull by e.g. `git fetch antis81 audio/gain:audio/gain`. Would help, getting some more feedback. Other than that, stay tuned and sorry for any inconvenience that might have been caused by this topic. :)
