### ISSUE TITLE
qtox: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#2740]
while waiting RPM repository, i'm downloading nightly build from:
https://build.tox.chat/view/Clients/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact 
and when i try to run qtox i see:

```
qtox: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

run on Fedora 23 with XFCE

**Comment by Zer0-One** [comment]
Someone needs to put together proper RPMs for fedora and centos

**Comment by bitchecker** [comment]
@Zer0-One fedora or centos is the same things about libraries, naming and paths.
do you have some news about rpm repository?

**Comment by zetok** [comment]
@Zer0-One or make a proper static binary.

**Comment by Zer0-One** [comment]
@bitchecker No news regarding a repository for fedora and centos. There's no point in hosting it if no-one is building packages for it.

@tux3 do you want to package a static qTox for fedora and centos until someone decides to build a package for the shared build?

**Comment by tux3** [comment]
@Zer0-One The build OP used should be fixed to link to libcrypto statically, then it'll work for Fedora, Centos, Debian, etc. No need to make a new static build for Redhat.

**Comment by bitchecker** [comment]
@tux3 the application still doesn't works, just tried to download package and run it!

**Comment by agilob** [comment]
I get the same error, on startup but qTox works fine, I see it as a warning. It doesn't break anything for me.

**Comment by feeef** [comment]
I get the same error with the latest nightly build as well. It is not a warning for me, qTox doesn't want to start. I am also on fedora 23.

**Comment by bpaassen** [comment]
I'd like to confirm the bug. qtox does not start up for me with that same error message under Fedora 23.

**Comment by tux3** [comment]
A fix for this bug while we find a way to fix the packages is to run "sudo yum install openssl" to install the missing dependencies on your system.

**Comment by bitchecker** [comment]
@tux3 openssl is already installed on a normal system, in fact this is what i see:

```
# dnf install openssl
Last metadata expiration check performed 0:01:57 ago on Mon Jan 25 09:27:52 2016.
Package openssl-1:1.0.2e-3.fc23.x86_64 is already installed, skipping.
```

**Comment by feeef** [comment]
Same for me here with the same command as @bitchecker. Same result. 
I am on fedora 23.

**Comment by tux3** [comment]
So the package is asking for an outdated version of openssl then, that's even worse. I don't maintain this package but since clearly no one else does either I'll try to find a way to fix it.
I'm afraid until this is squared away RPM users would have to compile from source.

**Comment by bitchecker** [comment]
any updates?

**Comment by tux3** [comment]
We still don't have anyone in charge of RPM packages, and I'm afraid I don't really have the time to learn how to make them at the moment, so no real progress yet.

**Comment by bitchecker** [comment]
before domain change of tox project. there was an rpm repository!

if you have a spec file i'll try to work on it when i'll have time.

**Comment by tux3** [comment]
I wouldn't know if we still have a spec file, I'm not seeing anything on our Jenkins server

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by bitchecker** [comment]
at the moment, it seems to work!

**Comment by zetok** [comment]
Thanks for testing it quickly! :)

Closing, since it seems to work.
