### ISSUE TITLE
Unable to build 1.7.0

### ISSUE THREAD

**Issue by wDraw** [qTox/qTox#4030]
I've taken the 1.7.0 source code as a tar.gz from the releases section. I've installed all depends needed. Am using Debian 8. 
Ended up with:

**compiling src/friend.cpp
In file included from src/friend.cpp:26:0:
src/core/core.h:28:21: fatal error: tox/tox.h: No such file or directory
 #include <tox/tox.h>
                     ^
compilation terminated.
Makefile:4339: recipe for target 'friend.o' failed
make: *** [friend.o] Error 1**

What gives? What am I doing wrong?

**Comment by zetok** [comment]
>I've installed all depends needed.

You're still missing toxcore.

Also, you should check out https://github.com/qTox/qTox/pull/4022

**Comment by wDraw** [comment]
It seems I haven't installed all dependencies then. Sorry for the waste of time.

**Comment by wDraw** [comment]
Ok, so I've compiled and installed toxcore, I get now:

**In file included from src/core/coreav.h:27:0,
                 from src/nexus.cpp:24:
src/core/toxcall.h:10:23: fatal error: tox/toxav.h: No such file or directory
 #include <tox/toxav.h>
                       ^
compilation terminated.
Makefile:4420: recipe for target 'nexus.o' failed
make: *** [nexus.o] Error 1**

**Comment by zetok** [comment]
Your toxcore is missing AV.

**Comment by zetok** [comment]
Use [`bootstrap.sh`](https://github.com/qTox/qTox/blob/master/bootstrap.sh) – it'll either compile toxcore correctly, or it'll error out (in which case you know that you're missing dependencies).

**Comment by wDraw** [comment]
I now get:
**error: pathspec 'tags/v0.1.0' did not match any file(s) known to git.**

In my opinion the "Building packages" section, needs to be before the "Compile qTox" section, to avoid confusion.

**Comment by zetok** [comment]
>error: pathspec 'tags/v0.1.0' did not match any file(s) known to git.

Corrected in #4031.

>In my opinion the "Building packages" section, needs to be before the "Compile qTox" section, to avoid confusion.

This section is haven't been touched/revised in a very long time, I have no idea whether that stuff even works at all.

**Comment by wDraw** [comment]
Even after changing to 0.1.2 it still doesn't work. I don't know what should be done to the docs, but it's confusing for newcomers.

**Comment by zetok** [comment]
>Even after changing to 0.1.2 it still doesn't work.

What was the exact command & error?

>I don't know what should be done to the docs, but it's confusing for newcomers.

Right. I was thinking about simplifying the docs by pointing to `simple_make.sh` and `bootstrap.sh` scripts. What do you think about it?

Also, which parts exactly in the documentation are confusing?

**Comment by wDraw** [comment]
> What was the exact command & error?

Well I just recompiled toxcore with the 0.1.2 tag and after running `./bootstrap.sh` I got the same error as before.

> **error: pathspec 'tags/v0.1.0' did not match any file(s) known to git.**

About the docs I think something like "Common Errors" could be added as a section, to help not so good with git or linux people.

**Comment by zetok** [comment]
>Well I just recompiled toxcore with the 0.1.2 tag and after running ./bootstrap.sh I got the same error as before.

Oops. Sorry, I've just figured out that the fix (1d98a97e3b8373d351f63d2da1fb3191d8f62690) to the bootstrap.sh was made after v1.7.0 was released – if you're using the version from v1.7.0 tarball it's not going to work.

>About the docs I think something like "Common Errors" could be added as a section, to help not so good with git or linux people.

https://github.com/qTox/qTox/wiki/Troubleshooting-builds

**Comment by wDraw** [comment]
> Oops. Sorry, I've just figured out that the fix (1d98a97) to the bootstrap.sh was made after v1.7.0 was released – if you're using the version from v1.7.0 tarball it's not going to work.

Thanks, saved me some headaches.

> https://github.com/qTox/qTox/wiki/Troubleshooting-builds

Oh sorry, forgot about the wiki.
