### ISSUE TITLE
Improper scaling in 1.11.0

### ISSUE THREAD

**Issue by catscratchedme** [qTox/qTox#4687]
##### Brief Description

OS: Windows 8.1
qTox version: v1.11.0
Commit hash: 66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore: 0.1.9
Qt: 5.6.2
Hardware: 
…

Reproducible: Always

##### Steps to reproduce

1. Open qTox

##### Observed Behavior
The scaling is not correct for 1080p screen. Buttons are large and pixelated, user avatars are pixelated, and chat spacing is incorrect and overlapping

##### Expected Behavior
Proper scaling, like there was in the previous version before I upgraded to 1.11. (I was using 1.9.0 before I upgraded).

##### Additional Info
Screenshot of the improperly scaled UI - 
<img width="785" alt="qtox github report" src="https://user-images.githubusercontent.com/29561518/30792001-f4c76510-a184-11e7-8730-8c4bc9bf009a.png">
https://i.imgur.com/IqbnAJx.png

**Comment by sudden6** [comment]
Do you use any settings for HiDPI displays?

**Comment by catscratchedme** [comment]
I've tried both checking and unchecking the Disable display scaling on high DPI settings.

1.9.0 worked fine on the same computer/screen.
<img width="275" alt="qtox shortcut" src="https://user-images.githubusercontent.com/29561518/30815944-9d448d14-a1e2-11e7-9951-52cd35d1d753.png">

**Comment by sudden6** [comment]
did the 1.9 build you used before have a different Qt version?
Also maybe it's already fixed in the new release (should be out in a few days).

**Comment by catscratchedme** [comment]
Hi sudden6!

I downgraded to 1.9.0 to check: it had Qt version 5.5.1.

This is the version info for 1.9.0 (which has proper UI scaling):

OS: Windows / OS X / Linux (include version and/or distro)
qTox version: v1.9.0-104-g5d117e6
Commit hash: 5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore: 0.1.8
Qt: 5.5.1

**Comment by catscratchedme** [comment]
Improper scaling is still present in 1.12.1:

OS: Windows 8.1
qTox version: v1.12.1
Commit hash: d65c30b879ee2f00c16816aa332567fd627c0b2b
toxcore: 0.1.10
Qt: 5.6.3

**Comment by sudden6** [comment]
This bug is multiple Qt and qTox versions old, closing.
