### ISSUE TITLE
autostart checkbox do nothing

### ISSUE THREAD

**Issue by koshakm5** [qTox/qTox#4865]
OS: Windows 7 x64
qTox version: v1.13.0
Commit hash: af1aebf
toxcore: 0.1.10
Qt: 5.9.3

Reproducible: Always

**Comment by sudden6** [comment]
Probably same reason as #4860 should be fixed in the next nightly.

**Comment by koshakm5** [comment]
@sudden6 checked 7ad68e2, seems to be fine

**Comment by ghost** [comment]
I still have that issue v1.13.0 Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
and Windows 7 x64

**Comment by anthonybilinski** [comment]
@darutse this sounds much more like https://github.com/qTox/qTox/issues/5025 to me than #4860.

#5025 was only fixed in v1.14.1 (you're on v1.13.0). Can you try [updating](https://github.com/qTox/qTox#readme) to v1.14.1 and see if the problem goes away?

**Comment by ghost** [comment]
ok I took nightly and without installing it it seems to work.
