### ISSUE TITLE
Minor: System tray icon setting ignored for MATE desktop environment, but does goes away when set

### ISSUE THREAD

**Issue by railhoff2** [qTox/qTox#5537]
##### Brief Description

OS: Linux Mint MATE 19.1 64 bit
qTox version: 1.16.3 (Appimage)
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce

1. Install Linux Mint MATE 19.1 64 bit in a VM.
2. Download and run the qTox Appimage, or run it any other way.
3. Navigate to settings -> general -> "Show system tay icon". Uncheck it. Note that the system tray icon disappears.
4. Exit and then restart qTox. Note that the system tray icon has reappeared. Repeating step 4 will hide it again.

##### Observed Behavior

System tray icon hidden state isn't acted upon at startup.

##### Expected Behavior

System tray icon should be hidden when the box is unchecked, and qTox is restarted.
##### Additional Info
Workaround: manually go into the menu at each qTox start to disable the system tray icon. Very minor bug due to this workaround existing.

**Comment by sudden6** [comment]
Your AppImage is quite old it could be that the problem is already solved on master, can you try building a newer version using https://github.com/qTox/qTox/blob/master/appimage/build-appimage.sh and report back?

**Comment by railhoff2** [comment]
Good point. I just built the latest, but non appimage version from source. Used 'git clone https://github.com/qTox/qTox' and the simple_make.sh. Unfortunately, I'm still seeing the same thing. The version I built is:
You are using qTox version v1.16.3-275-g089d6a8.
Commit hash: 089d6a8e7a838b41c213781abea782c7035e71fb
Which looks to have the very latest changes in it.

**Comment by sudden6** [comment]
Yes, you are on a recent version now, I re-tagged the bug accordingly.

**Comment by railhoff2** [comment]
Thanks sudden6. Absolutely loving qTox BTW, thanks so much for your work on it (and all others involved!).
