### ISSUE TITLE
qTox unable to recognize my webcam

### ISSUE THREAD

**Issue by mbnoimi** [qTox/qTox#6059]
##### Brief Description

OS: Linux Mint 19.3 xfce x64
qTox version: 1.16.3 (from [flathub](https://flathub.org/apps/details/io.github.qtox.qTox))
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.10
Qt:  5.12.6
…

Reproducible: Always

##### Steps to reproduce

1. Settings -> Audio/Video -> Video Settings
2. Rescan devices
![image](https://user-images.githubusercontent.com/284547/78210976-768b5700-74b4-11ea-975a-8bea4f7d4502.png)
3. Unable to recognize my webcam
4. `v4l2-ctl --all`
```
Driver Info (not using libv4l2):
	Driver name   : uvcvideo
	Card type     : TOSHIBA Web Camera - HD: TOSHIB
	Bus info      : usb-0000:00:14.0-10
	Driver version: 5.3.18
	Capabilities  : 0x84A00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 1280/720
	Pixel Format      : 'YUYV'
	Field             : None
	Bytes per Line    : 2560
	Size Image        : 1843200
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1280, Height 720
	Default     : Left 0, Top 0, Width 1280, Height 720
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 1280, Height 720
Selection: crop_bounds, Left 0, Top 0, Width 1280, Height 720
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 10.000 (10/1)
	Read buffers     : 0
                     brightness 0x00980900 (int)    : min=0 max=100 step=1 default=50 value=50
                       contrast 0x00980901 (int)    : min=0 max=100 step=1 default=32 value=32
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=32 value=32
                            hue 0x00980903 (int)    : min=-4 max=4 step=1 default=0 value=0
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=1 max=16 step=1 default=8 value=8
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=10 default=5000 value=5000 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=20 step=1 default=4 value=4
         backlight_compensation 0x0098091c (int)    : min=0 max=1 step=1 default=0 value=0
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=1
```

##### Expected Behavior
Recognizing my webcam easily just like `cheese` and `skypeforlinux`

**Comment by mbnoimi** [comment]
```
$ v4l-info

### v4l2 device info [/dev/video0] ###
general info
    VIDIOC_QUERYCAP
	driver                  : "uvcvideo"
	card                    : "TOSHIBA Web Camera - HD: TOSHIB"
	bus_info                : "usb-0000:00:14.0-10"
	version                 : 5.3.18
	capabilities            : 0x84a00001 [VIDEO_CAPTURE,?,?,STREAMING,(null)]

standards

inputs
    VIDIOC_ENUMINPUT(0)
	index                   : 0
	name                    : "Camera 1"
	type                    : CAMERA
	audioset                : 0
	tuner                   : 0
	std                     : 0x0 []
	status                  : 0x0 []

video capture
    VIDIOC_ENUM_FMT(0,VIDEO_CAPTURE)
	index                   : 0
	type                    : VIDEO_CAPTURE
	flags                   : 0
	description             : "YUYV 4:2:2"
	pixelformat             : 0x56595559 [YUYV]
    VIDIOC_ENUM_FMT(1,VIDEO_CAPTURE)
	index                   : 1
	type                    : VIDEO_CAPTURE
	flags                   : 1
	description             : "Motion-JPEG"
	pixelformat             : 0x47504a4d [MJPG]
    VIDIOC_G_FMT(VIDEO_CAPTURE)
	type                    : VIDEO_CAPTURE
	fmt.pix.width           : 1280
	fmt.pix.height          : 720
	fmt.pix.pixelformat     : 0x56595559 [YUYV]
	fmt.pix.field           : NONE
	fmt.pix.bytesperline    : 2560
	fmt.pix.sizeimage       : 1843200
	fmt.pix.colorspace      : SRGB
	fmt.pix.priv            : 4276996862

controls
    VIDIOC_QUERYCTRL(BASE+0)
	id                      : 9963776
	type                    : INTEGER
	name                    : "Brightness"
	minimum                 : 0
	maximum                 : 100
	step                    : 1
	default_value           : 50
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+1)
	id                      : 9963777
	type                    : INTEGER
	name                    : "Contrast"
	minimum                 : 0
	maximum                 : 100
	step                    : 1
	default_value           : 32
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+2)
	id                      : 9963778
	type                    : INTEGER
	name                    : "Saturation"
	minimum                 : 0
	maximum                 : 100
	step                    : 1
	default_value           : 32
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+3)
	id                      : 9963779
	type                    : INTEGER
	name                    : "Hue"
	minimum                 : -4
	maximum                 : 4
	step                    : 1
	default_value           : 0
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+12)
	id                      : 9963788
	type                    : BOOLEAN
	name                    : "White Balance Temperature, Auto"
	minimum                 : 0
	maximum                 : 1
	step                    : 1
	default_value           : 1
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+16)
	id                      : 9963792
	type                    : INTEGER
	name                    : "Gamma"
	minimum                 : 1
	maximum                 : 16
	step                    : 1
	default_value           : 8
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+24)
	id                      : 9963800
	type                    : MENU
	name                    : "Power Line Frequency"
	minimum                 : 0
	maximum                 : 2
	step                    : 1
	default_value           : 1
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+26)
	id                      : 9963802
	type                    : INTEGER
	name                    : "White Balance Temperature"
	minimum                 : 2800
	maximum                 : 6500
	step                    : 10
	default_value           : 5000
	flags                   : INACTIVE
    VIDIOC_QUERYCTRL(BASE+27)
	id                      : 9963803
	type                    : INTEGER
	name                    : "Sharpness"
	minimum                 : 0
	maximum                 : 20
	step                    : 1
	default_value           : 4
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+28)
	id                      : 9963804
	type                    : INTEGER
	name                    : "Backlight Compensation"
	minimum                 : 0
	maximum                 : 1
	step                    : 1
	default_value           : 0
	flags                   : unknown
```

**Comment by samyakahuja** [comment]
I am having the same issue on v1.16.3 (form arch). Screen capture is successful but qtox is unable to recognize my video device. I am able to see the output from the device using `ffplay /dev/video0` just fine. 

Output of `v4l2-ctl --list-formats --list-devices`

```
Dummy video device (0x0000) (platform:v4l2loopback-000):
        /dev/video0

ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'YU12' (Planar YUV 4:2:0)
```

The output of `v4l2-ctl --all`

```
Driver Info: 
        Driver name      : v4l2 loopback 
        Card type        : Dummy video device (0x0000) 
        Bus info         : platform:v4l2loopback-000 
        Driver version   : 4.19.113 
        Capabilities     : 0x85208003 
                Video Capture 
                Video Output 
                Video Memory-to-Memory 
                Read/Write 
                Streaming 
                Extended Pix Format 
                Device Capabilities 
        Device Caps      : 0x85208003 
                Video Capture 
                Video Output 
                Video Memory-to-Memory 
                Read/Write 
                Streaming 
                Extended Pix Format 
                Device Capabilities 
Priority: 0 
Video input : 0 (loopback: ok) 
Video output: 0 (loopback in) 
Format Video Capture: 
        Width/Height      : 472/591 
        Pixel Format      : 'YU12' (Planar YUV 4:2:0) 
        Field             : None 
        Bytes per Line    : 472 
        Size Image        : 418428 
        Colorspace        : sRGB 
        Transfer Function : Default (maps to sRGB) 
        YCbCr/HSV Encoding: Default (maps to ITU-R 601) 
        Quantization      : Default (maps to Limited Range) 
        Flags             : 
Format Video Output: 
        Width/Height      : 472/591 
        Pixel Format      : 'YU12' (Planar YUV 4:2:0) 
        Field             : None 
        Bytes per Line    : 472 
        Size Image        : 418428 
        Colorspace        : sRGB 
        Transfer Function : Default (maps to sRGB) 
        YCbCr/HSV Encoding: Default (maps to ITU-R 601) 
        Quantization      : Default (maps to Limited Range) 
        Flags             : 
Streaming Parameters Video Capture: 
        Frames per second: 30.000 (30/1) 
        Read buffers     : 2 
Streaming Parameters Video Output: 
        Frames per second: 30.000 (30/1) 
        Write buffers    : 2 
User Controls 
                    keep_format 0x0098f900 (bool)   : default=0 value=0 
              sustain_framerate 0x0098f901 (bool)   : default=0 value=0 
                        timeout 0x0098f902 (int)    : min=0 max=100000 step=1 default=0 value=0 
               timeout_image_io 0x0098f903 (bool)   : default=0 value=0 
```

**Comment by mbnoimi** [comment]
[qtox.log](https://github.com/qTox/qTox/files/4418977/qtox.log)

**Comment by sudden6** [comment]
Can you try a nightly build from here: https://github.com/qTox/qTox-nightly-releases/releases (backup your profile first).

Also please post the output of qTox when you try to open the video device.

**Comment by mbnoimi** [comment]
> Can you try a nightly build from here: https://github.com/qTox/qTox-nightly-releases/releases (backup your profile first).
> 
> Also please post the output of qTox when you try to open the video device.

Works with AppImage but I wonder when qTox will be released (the last release was since 2 years ago)?

**Comment by marcecj** [comment]
I have this issue, too, but with the flatpak image.
```
% flatpak info --user io.github.qtox.qTox

qTox - Powerful Tox chat client that follows the Tox design guidelines.

         Kennung: io.github.qtox.qTox
             Ref: app/io.github.qtox.qTox/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 1.17.2
         License: GPL-3.0
        Ursprung: flathub
      Collection: org.flathub.Stable
    Installation: user
       Installed: 9,5 MB
Laufzeitumgebung: org.kde.Platform/x86_64/5.14
             Sdk: org.kde.Sdk/x86_64/5.14

          Commit: 1c5ffc030dda54792e235b7ea73824e472a615925e83100b4d305dbd30e79792
          Parent: 038b6148610de30c4adab7b2993d24dd1206447c857e223412a19b6867d7b46b
         Subject: update qTox to 1.17.2 (3a71c580)
            Date: 2020-05-07 20:25:29 +0000
```
  As in #6063, I *can* select the Webcam's microphone as input.  I can see the webcam image with ` mpv av://v4l2://dev/video0`, so it didn't suddenly stop working.  "Rescan Devices" does not help, and the program output does not seem particularly informative.
```
% flatpak --user run io.github.qtox.qTox
[20:25:40.580 UTC] persistence/settings.cpp:121 : Debug: "Loading settings from /home/marcec/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[20:25:40.687 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  9204447637939282818
[20:25:40.687 UTC] main.cpp:308 : Debug: commit:  465d82606813439ee14425f7462903bb39f2da30
[20:25:45.812 UTC] persistence/profile.cpp:146 : Debug: Loading tox save  "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.tox"
[20:25:46.020 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.ini"
[20:25:46.021 UTC] core/toxoptions.cpp:110 : Debug: Core starting with IPv6 enabled
[20:25:46.221 UTC] persistence/db/rawdatabase.cpp:321 : Debug: Highest supported SQLCipher params on this system are "4.0 default"
[20:25:46.222 UTC] persistence/db/rawdatabase.cpp:292 : Debug: Setting SQLCipher "4.0 default" parameters
[20:25:46.223 UTC] persistence/db/rawdatabase.cpp:199 : Info: Opened database with SQLCipher "4.0 default" parameters
[20:25:46.234 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.ini"
[20:25:46.235 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/marcec/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[20:25:46.244 UTC] nexus.cpp:86 : Debug: Starting up
[20:25:47.275 UTC] persistence/profile.cpp:318 : Debug: Self avatar not found, will broadcast empty avatar to friends
[20:25:47.472 UTC] plugins/hunspell/hunspelldict.cpp:47 : Warning: Unable to find dictionary for "de_DE" in path "/usr/share/runtime/locale/de/share/de/hunspell/de_DE"
[20:25:48.722 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[20:25:48.723 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[20:25:50.684 UTC] net/updatecheck.cpp:89 : Info: qTox is up to date
[20:25:53.224 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[20:25:53.225 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[20:25:56.091 UTC] core/core.cpp:443 : Debug: Connected to the DHT
[20:26:00.816 UTC] video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
[20:26:00.816 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:26:00.816 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:26:00.816 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:26:00.816 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:26:00.816 UTC] audio/backend/openal.cpp:397 : Debug: Opening audio input "Webcam C270 Mono"
[20:26:00.816 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:26:00.816 UTC] video/camerasource.cpp:284 : Warning: Failed to open device!
[20:26:02.700 UTC] audio/backend/openal.cpp:423 : Debug: Opened audio input "Webcam C270 Mono"
[20:26:02.707 UTC] audio/backend/openal.cpp:337 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[20:26:02.707 UTC] audio/backend/openal.cpp:441 : Debug: Opening audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:26:02.719 UTC] audio/backend/openal.cpp:453 : Debug: Opened audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:26:02.754 UTC] audio/backend/openal.cpp:278 : Debug: Audio source 1 created. Sources active: 1
[20:27:08.274 UTC] audio/backend/openal.cpp:306 : Debug: Audio source 1 deleted. Sources active: 0
[20:27:08.282 UTC] audio/backend/openal.cpp:609 : Debug: Closing audio output
[20:27:08.282 UTC] audio/backend/openal.cpp:359 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[20:27:08.282 UTC] audio/backend/openal.cpp:583 : Debug: Closing audio input
[20:27:08.285 UTC] video/camerasource.cpp:388 : Debug: Closing device "none" subscriptions: 0
[20:27:13.087 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:27:13.087 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:27:13.087 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:27:13.087 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:27:13.087 UTC] audio/backend/openal.cpp:397 : Debug: Opening audio input "Webcam C270 Mono"
[20:27:13.089 UTC] video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
[20:27:13.089 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:27:13.089 UTC] video/camerasource.cpp:284 : Warning: Failed to open device!
[20:27:13.091 UTC] audio/backend/openal.cpp:423 : Debug: Opened audio input "Webcam C270 Mono"
[20:27:13.092 UTC] audio/backend/openal.cpp:337 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[20:27:13.092 UTC] audio/backend/openal.cpp:441 : Debug: Opening audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:27:13.096 UTC] audio/backend/openal.cpp:453 : Debug: Opened audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:27:13.132 UTC] audio/backend/openal.cpp:278 : Debug: Audio source 1 created. Sources active: 1
[20:27:32.780 UTC] audio/backend/openal.cpp:306 : Debug: Audio source 1 deleted. Sources active: 0
[20:27:32.784 UTC] audio/backend/openal.cpp:609 : Debug: Closing audio output
[20:27:32.784 UTC] audio/backend/openal.cpp:359 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[20:27:32.785 UTC] audio/backend/openal.cpp:583 : Debug: Closing audio input
[20:27:32.789 UTC] video/camerasource.cpp:388 : Debug: Closing device "none" subscriptions: 0
[20:27:49.306 UTC] video/camerasource.cpp:271 : Debug: Opening device "none" subscriptions: 1
[20:27:49.306 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:27:49.306 UTC] video/camerasource.cpp:284 : Warning: Failed to open device!
[20:27:49.306 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:27:49.306 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:27:49.306 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:27:49.306 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:27:49.306 UTC] audio/backend/openal.cpp:397 : Debug: Opening audio input "Webcam C270 Mono"
[20:27:51.191 UTC] audio/backend/openal.cpp:423 : Debug: Opened audio input "Webcam C270 Mono"
[20:27:51.199 UTC] audio/backend/openal.cpp:337 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[20:27:51.199 UTC] audio/backend/openal.cpp:441 : Debug: Opening audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:27:51.210 UTC] audio/backend/openal.cpp:453 : Debug: Opened audio output "RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)"
[20:27:51.228 UTC] audio/backend/openal.cpp:278 : Debug: Audio source 1 created. Sources active: 1
[20:28:02.029 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:28:02.029 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:28:02.029 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:28:02.029 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:28:02.306 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:28:02.306 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:28:02.306 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:28:02.306 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:28:02.487 UTC] video/cameradevice.cpp:541 : Warning: No valid input format found
[20:28:02.487 UTC] widget/form/settings/avform.cpp:393 : Debug: available Modes:
[20:28:02.487 UTC] widget/form/settings/avform.cpp:225 : Critical: Trying to select best mode from empty modes list
[20:28:02.488 UTC] widget/form/settings/avform.cpp:302 : Debug: selected Modes:
[20:28:54.884 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/marcec/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[20:28:54.900 UTC] persistence/settings.cpp:759 : Debug: Saving personal settings at  "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.ini"
[20:28:54.916 UTC] audio/backend/openal.cpp:306 : Debug: Audio source 1 deleted. Sources active: 0
[20:28:54.924 UTC] audio/backend/openal.cpp:609 : Debug: Closing audio output
[20:28:54.925 UTC] audio/backend/openal.cpp:359 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[20:28:54.926 UTC] audio/backend/openal.cpp:583 : Debug: Closing audio input
[20:28:54.931 UTC] video/camerasource.cpp:388 : Debug: Closing device "none" subscriptions: 0
[20:28:55.171 UTC] persistence/profile.cpp:358 : Debug: Saving tox save to  "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.tox"
[20:28:55.176 UTC] persistence/settings.cpp:759 : Debug: Saving personal settings at  "/home/marcec/.var/app/io.github.qtox.qTox/config/tox/marcecj.ini"
[20:28:55.187 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /home/marcec/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[20:28:55.191 UTC] main.cpp:75 : Debug: Cleanup success
[20:28:55.209 UTC] main.cpp:417 : Debug: Exit with status 0
```

**Comment by sudden6** [comment]
@marcecj Does it work with the AppImage? I'm pretty sure with Flatpak it could be a permission problem, but I don't know enough about flatpak to say for sure.

**Comment by marcecj** [comment]
I didn't try the AppImage, but downgrading the flatpak version to 1.16.3 makes webcam access work again.  Here's what I'm using now:
```
% flatpak --user info io.github.qtox.qTox

qTox - Powerful Tox chat client that follows the Tox design guidelines.

         Kennung: io.github.qtox.qTox
             Ref: app/io.github.qtox.qTox/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         License: GPL-3.0
        Ursprung: flathub
      Collection: org.flathub.Stable
    Installation: user
       Installed: 20,4 MB
Laufzeitumgebung: org.kde.Platform/x86_64/5.11
             Sdk: org.kde.Sdk/x86_64/5.11

          Commit: 30426649d38730945329a68d3e29cfeb690043998b68b0813b270f7dd2615378
          Parent: d0a7ab4ec7f71898cbe1524f03a2927ae7bc19225f650d988e6e08fc83977a13
         Subject: update to qTox release v1.16.3 (812504f3)
            Date: 2018-07-22 08:57:39 +0000
```
I'm not sure whether this helps or not, as it uses a different version of the KDE runtime.  I upgraded and downgraded again to be more sure that this was deterministic, and it was.  I then tried out the other two commits that are in-between that and the current version:
- 7414818d1228fbdc97f49bd97b8360f824e63392387f3092ad17c4360950f160 works
- 038b6148610de30c4adab7b2993d24dd1206447c857e223412a19b6867d7b46b is broken

I suspect the problem here has to do with the switch to the `ffmpeg-full` extension in https://github.com/flathub/io.github.qtox.qTox/commit/3d1946d03a87fb2f6b37958af6adde763adee27d.

**Comment by Nokia808** [comment]
Hi. Today I removed .rpm package of this great program (from RPMFusion repositories) that I installed it & used it since years without problem. It was 1.16.xxxxxxx version. After removing .rpm package I installed flatpak package from FlatHub & - unfortunately - I shocked by this issue ! I posted about this in flatpak repository - see:

https://github.com/flathub/io.github.qtox.qTox/issues/15

My aim from shifting to flatpak package was to obtain the latest version of this program .... Now I'm version 1.17.2

But, when I saw this issue here, it seem that this issue is general !

I'm on Fedora Linux 30 X64 bit Cinnamon edition, installed on Lenovo ThinkPad e550 with Intel core i7 5500 CPU @ 2.40 GH X 2, RAM = 8 GB, HHD = 1 TB, Hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)

**Comment by sudden6** [comment]
> but downgrading the flatpak version to 1.16.3 makes webcam access work

This is interesting, I tested with 1.16.3 too, but couldn't get webcam to work, so I thought it's an existing issue.

**Comment by marcecj** [comment]
> > but downgrading the flatpak version to 1.16.3 makes webcam access work
> 
> This is interesting, I tested with 1.16.3 too, but couldn't get webcam to work, so I thought it's an existing issue.

(TLDR: the ffmpeg-full runtime does not support V4L)

So to be clear, only *some* versions of the 1.16.3 flatpak work.  To summarize my experience:
- qTox 1.16.3 on Gentoo *works* (this is what I am trying to replace with flatpak)
- qTox 1.16.3 on openSUSE tumbleweed *works* (I've upgraded to 1.17.2 recently, but haven't had a chance to use it yet)
- qTox 1.16.3 (flatpak) commit 30426649d38730945329a68d3e29cfeb690043998b68b0813b270f7dd2615378 *works*
- qTox 1.6.13 (flatpak) commit 7414818d1228fbdc97f49bd97b8360f824e63392387f3092ad17c4360950f160 *works*
- qTox 1.6.13 (flatpak) commit 038b6148610de30c4adab7b2993d24dd1206447c857e223412a19b6867d7b46b *fails*
- qTox 1.17.2 (flatpak) commit 1c5ffc030dda54792e235b7ea73824e472a615925e83100b4d305dbd30e79792 *fails*

(I have no idea where these commits actually are, they're what is referred to as `commit` in the `flatpak info` output above.)

The only commits to the flatpak repository between the version that worked and the version that failed are:
- https://github.com/flathub/io.github.qtox.qTox/commit/3d1946d03a87fb2f6b37958af6adde763adee27d
- https://github.com/flathub/io.github.qtox.qTox/commit/040c3ce800e4cda709963e323ef6b38391dcf606

The second one only adds a patch that changes some text, while the first makes some massive changes: it removes the internal build of ffmpeg with a flapak dependency, includes Tcl (???), and updates various dependencies.  My bet is on the ffmpeg change, as previously commented, but I could be wrong, of course, what with me not knowing the code.  Looking at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/include/ffmpeg.yml, however, (which looks like the build configuration for ffmpeg-full), searching for `v4l` comes up empty.  However, according to ffmpeg's `configure` file you must pass `--enable-libv4l2`, since it defaults to off (the flatpak build also notably passes `--disable-everything` to `configure`).

So it looks pretty clear to me that the `ffmpeg-full` runtime just doesn't support V4L, and thus simply is incapable of accessing webcams.  Therefore I think the short-term workaround is to build ffmpeg locally again.  I also found [this upstream issue](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/941) with the runtime.

**Comment by sudden6** [comment]
@marcecj Thank you for the detailed research. It seems we will need to revert to building ffmpeg ourselfes for now.

I created an upstream issue here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1034

**Comment by marcecj** [comment]
Hi again, are you still going to add the workaround to the flatpak build, or are you going to wait for a new version of the ffmpeg-full runtime?

**Comment by sudden6** [comment]
It doesn't really look like upstream is going to include the requested changes :(

**Comment by Nokia808** [comment]
@sudden6 
No ! No ! The upstream fix it ! Kindly, look for this:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2979

**Comment by sudden6** [comment]
@Nokia808 Thanks for the link! Seems we just have to wait and update to the sdk :)

**Comment by marcecj** [comment]
That PR is still open, but it's existence has me slightly optimistic now, thanks for linking!

**Comment by marcecj** [comment]
> That PR is still open, but it's existence has me slightly optimistic now, thanks for linking!

Alright, it was merged and is now in [freedesktop-sdk-20.08beta.5](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-20.08beta.5)!

**Comment by Nokia808** [comment]
@sudden6 
Hi. The final release of freedesktop-sdk 20.08 had been released 5 days ago ! Kindly, see it at:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases

Is it time to fix qTox flatpak package or we still need to wait more time ?

**Comment by sudden6** [comment]
With https://github.com/qTox/qTox/pull/6228 merged, this should be fixed in the next nightly build.

I also marked it for backporting into the next point release.

**Comment by marcecj** [comment]
I'm sorry, but it still doesn't work, see https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1034#note_438993517 for details.

**Comment by benjamb** [comment]
This should hopefully be fixed in freedesktop-sdk 22.08. Could you try updating the ffmpeg-full version and reporting back whether that works?
