### ISSUE TITLE
Memory leak when clicking Add or Settings tab repeatedly

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#658]
Some non-scientific testing showed clicking the + or the cog repeatedly peaked at adding ~10MiB to the overall private memory usage and never gets freed. Could it be down to the HTML layout operation continuously processing the same code and not GCing the heap?

I've also noticed qTox has gradually increased its general memory usage too.

**Comment by zetok** [comment]
Huh, nice catch.

I was able to reproduce - it requires **a lot** of switching between `Add` and `Settings` pages, and increase in memory usage is not all that visible - ~14MB after I've switched between those views ~dozens (if not hundreds) of times.

**Comment by tux3** [comment]
It's really hard to find the root cause of this bug, I'm not convinced this isn't a leak in Qt itself.
A solution could be to replace the current manual layout switches with a QStackedWidget

**Comment by sudden6** [comment]
this seems fixed at https://github.com/tux3/qTox/commit/252c9c8fae35f0258381537fee444b5eb02a9d7c

**Comment by zetok** [comment]
Re-opening; I can still reproduce it on 252c9c8fae35f0258381537fee444b5eb02a9d7c

**Comment by sudden6** [comment]
how often did you switch tabs?

**Comment by zetok** [comment]
As fast as I could, which would be about 1-2 switches per second.

**Comment by anoadragon453** [comment]
Couldn't reproduce on latest build.

**Comment by zetok** [comment]
Also couldn't reproduce on 9694d6b6d434bb7557c9766e89dce5fb4cb89502, thus closing.

If someone can still reproduce, please comment for reopen.
