### ISSUE TITLE
Mac OS - will not start after installing latest ver

### ISSUE THREAD

**Issue by cjpit** [qTox/qTox#787]
As per #769 - I've put a comment in there, the cocoa file seems to be there, just wondering what the fix is? Have 2 new users  with same problem...

Thanks

**Comment by cjpit** [comment]
I don't know if this may help also
http://qt-project.org/forums/viewthread/34860

**Comment by stqism** [comment]
Howdy, we're currently working on figuring out the issue. For the time being, mind telling me if this works? https://jenkins.libtoxcore.so/job/qTox%20OS%20X/405/artifact/qtox.pkg

**Comment by iShift** [comment]
I have same problem, crash log - https://ezcrypt.it/zdAn#RkJ75f2i5MMRdTzJZMgQ5dfb

**Comment by stqism** [comment]
Yeah, it's a bug in Qt 5.4, should be fixed soon.

**Comment by stqism** [comment]
@iShift @cjpit Try this: https://jenkins.libtoxcore.so/job/qTox%20OS%20X/lastSuccessfulBuild/artifact/qtox.pkg

**Comment by wliment** [comment]
mac osx10.10 install lastest pkg ,still crash.

**Comment by Derq** [comment]
the crash is still happening even on 10.9.5 as of the latest commit
is this a problem with the build or with Qt 5.3? I'm using 5.3 so far

**Comment by stqism** [comment]
@Derq @wliment @iShift @cjpit This issue should be resolved now, it won't crash anymore.

**Comment by wliment** [comment]
@Derq   i had install latest qt from homebrew ,but it still crash ;
this is crash log  https://ezcrypt.it/HeAn#uZD1NUTex7YOubhAZaKdXHVR

**Comment by Derq** [comment]
@wliment It's working for me, sadly i don't use 10.10 and I barely program I have no idea why it's not working, maybe compiling from a clean repository might help

**Comment by stqism** [comment]
@wliment, You don't need Qt installed to use it, just install this https://jenkins.libtoxcore.so/job/qTox%20OS%20X/lastSuccessfulBuild/artifact/qtox.pkg and then run `curl https://gist.githubusercontent.com/stqism/df6a7ef60c10c20789c9/raw/a7ad36d058670ae543192eadcbce1d0d88d02585/settings.ini > ~/Library/Preferences/tox/settings.ini`

**Comment by wliment** [comment]
thanks @stqism  follow you posts , qtox run regular.

**Comment by tux3** [comment]
Since we discontinued the previous OS X builds, this bug shouldn't apply anymore.
